services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    IAkumaI\SphinxsearchBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Exception,Pagerfanta,Sphinx}'
